### ISSUE TITLE
Action run ending "Error: Process completed with exit code 1."

### ISSUE THREAD

**Issue by mathiashro** [releasehub-com/github-action-create-pr-parent-submodule#1]
Currently I do get an exit code 1. I'm not sure if my setup is somehow wrong and how I can further troubleshoot the following issue:

```
Run git config user.name github-actions
  git config user.name github-actions
  git config user.email github-actions@github.com
  git submodule update --remote
  git checkout -b $GITHUB_RUN_ID
  git commit -am "updating submodules"
  git push --set-upstream origin $GITHUB_RUN_ID
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PARENT_REPOSITORY: <org>/<repo>
    CHECKOUT_BRANCH: main
    PR_AGAINST_BRANCH: main
    OWNER: <org>
Switched to a new branch '2140478299'
On branch 2140478299
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```

My action:
```
name: 'submodule update'
# When to start the job
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
# Run the job
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: '<org>/<repo>'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: '<org>'
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: run action
      id: run_action
      uses: releasehub-com/github-action-create-pr-parent-submodule@v1
      with: 
        github_token: ${{ secrets.SUBMODULE_UPDATE_SECRET }}
        parent_repository: ${{ env.PARENT_REPOSITORY }}
        checkout_branch: ${{ env.CHECKOUT_BRANCH}}
        pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
        owner: ${{ env.OWNER }}
```

I've also walked again via the nice post at https://thenewstack.io/how-to-trigger-github-actions-on-submodule-updates/ but still not finding the root cause.

Many thanks.
